project_id = "dqyqkeqdvsidmffaanys"

[functions.tapnation-business-checkout]
verify_jwt = true

[functions.tapnation-business-verify]
verify_jwt = true

[functions.tapnation-paystack-webhook]
verify_jwt = false

[functions.tapnation-store-order]
verify_jwt = false

[functions.cardence-yoco-webhook]
verify_jwt = false

[functions.cardence-book-shipment]
verify_jwt = true
